# Generated by Django 4.1.3 on 2022-11-21 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='category',
            name='text',
        ),
        migrations.AddField(
            model_name='category',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='son', to='essay.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='top_parent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
