# Generated by Django 4.1.3 on 2022-11-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0004_alter_category_options_essay_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='update_time',
            new_name='updated_time',
        ),
    ]
