# Generated by Django 4.1.3 on 2022-11-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0005_rename_create_time_category_created_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='update_time',
            new_name='updated_time',
        ),
    ]
