# Generated by Django 4.1.3 on 2022-12-01 06:33

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0009_alter_essay_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='正文'),
        ),
    ]
